server: common.h server_skelenton.cpp
	g++ -o server.out server_skelenton.cpp -lcrypto

client: common.h client_skelenton.cpp
	g++ -o client.out client_skelenton.cpp -lcrypto

time_attack:
	g++ -o time_attack.out time_attack.cpp

all: server client time_attack
